[supervisord]
nodaemon=true
user=root

# 1. Core Service
[program:core]
command=java -Xms64m -Xmx128m -Xss256k -jar /app/task-master-core.jar --server.port=8080
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# 2. Comment Service
[program:comment]
command=java -Xms32m -Xmx96m -Xss256k -jar /app/task-master-comment.jar --server.port=8081
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# 3. Reports Service
[program:reports]
command=java -Xms32m -Xmx96m -Xss256k -jar /app/task-master-reports.jar --server.port=8082
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# 4. Gateway Service
[program:gateway]
command=java -Xms32m -Xmx96m -Xss256k -jar /app/task-master-gateway.jar --server.port=8083 --SERVICES_BACKEND_URL=%(ENV_SERVICES_BACKEND_URL)s --SERVICES_COMMENT_URL=%(ENV_SERVICES_COMMENT_URL)s --SERVICES_REPORT_URL=%(ENV_SERVICES_REPORT_URL)s
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0